### ISSUE TITLE
Benthos templates should do some linting on config fields for components

### ISSUE THREAD

**Issue by mihaitodor** [redpanda-data/benthos#103]
Currently, setting a non-existent field on a component in a template does not trigger a linter error. For example:

`test.tmpl.yaml`
```yaml
name: test
type: input
status: experimental

mapping: |
  #!blobl

  root.generate.count = 0
  root.generate.foobar = "kaboom"
  root.generate.mapping = "root = \"\""
```

`test.yaml`
```yaml
input:
  test: {}
output:
  stdout: {}
```

```shell
$ benthos run --templates ./test.tmpl.yaml test.yaml 
```

doesn't complain about `generate.foobar` being an invalid field.
