### ISSUE TITLE
Error handling in the `retry` processor

### ISSUE THREAD

**Issue by mihaitodor** [redpanda-data/benthos#125]
Currently, the `retry` processor [scrubs](https://github.com/redpanda-data/benthos/blob/219c3a411197867e97648e5ae26eb864ac1235c5/internal/impl/pure/processor_retry.go#L224-L225) the error of the origin message. This can be confusing for users. Maybe it would be better to not scrub it at all and make sure it's set back to its original value if one of the child processors clears it? Or maybe it's best to scrub it and set it back if the child processors don't set some other error? Or append to it the error coming from child processors? Not sure what's the best tradeoff...

Here's a sample config to experiment with:

```yaml
input:
  generate:
    count: 1
    mapping: root = ""
  processors:
    - mapping: root = throw("kaboom")

  processors:
    - log:
        message: 'Before: ${! error() }'

    - retry:
        processors:
          - log:
              message: 'Inside: ${! error() }'

    - log:
        message: 'After: ${! error() }'

output:
  drop: {}
```
