### ISSUE TITLE
scanner not handling AWS SQS events correctly for empty files

### ISSUE THREAD

**Issue by hunarqa** [redpanda-data/benthos#137]
Benthos pushing SQS notification back into the queue when event triggered for empty files uploaded to an S3 bucket.
Multiple error messages as the following were seen in the logs:
"Pushing SQS notification back into the queue due to error: encountered an empty file for key 'example_1.csv'"

scanner was configured as the following:
```
     aws_s3:
          bucket: bucket_name
          region: us-west-2
          force_path_style_urls: false
          delete_objects: false
          scanner:
            csv:
              custom_delimiter: ','
              parse_header_row: true
              lazy_quotes: true
              continue_on_error: true
```
