### ISSUE TITLE
`file` input deletes empty files but doesn't actually process them

### ISSUE THREAD

**Issue by ligfx** [redpanda-data/benthos#160]
For instance, try `echo -n > inputs/emptyfile` vs `echo > inputs/newlinefile`. The empty file will send the message `Consuming from file 'inputs/emptyfile'` to the debug logger and will delete the file, but won't actually run any processors or outputs.

Example connect config:

```yaml
logger:
  level: DEBUG

input:
  file:
    delete_on_finish: true
    paths:
    - inputs/*

pipeline:
  processors:
  - log:
      message: "This won't appear for empty files!"
```
