### ISSUE TITLE
Benthos tests don't recognise template components

### ISSUE THREAD

**Issue by mihaitodor** [redpanda-data/benthos#194]
Given this `foo.tmpl.yaml`:

```
name: foobar
type: processor
fields:
  - name: foo
    type: string

mapping: |
  #!blobl
  root.mapping = "root.foo = \"" + this.foo + "\""
```

And `foo.yaml`:

```
input:
  generate:
    count: 1
    mapping: root = ""

pipeline:
    processors:
      - foobar:
          foo: bar

output:
  stdout: {}

tests:
  - name: example test
    target_processors: '/pipeline/processors'
    environment: {}
    input_batch:
      - content: ""
    output_batches:
      -
        - json_equals: '{ "foo": "bar" }'
```

This command:

```shell
$ benthos test -t foo.tmpl.yaml foo.yaml
```

Fails with:

```
```
