### ISSUE TITLE
status code of a `http_client` under output.

### ISSUE THREAD

**Issue by Sidcapman** [redpanda-data/benthos#213]
I am encountering an issue when attempting to capture the `http_status_code` from an HTTP endpoint using Benthos. Despite configuring the `extract_headers` to include the `http_status_code`, the logged output consistently returns <nil> for the status code.

this is the method is tried. 
i used "http_status_code" because i saw in the code, the `http_status_code` is being set in the repo: 
https://github.com/redpanda-data/benthos/blob/main/internal/httpclient/client.go#L219

I have a benthos/connect config like this: 

```yaml
http:
  address: 0.0.0.0:4195
input:
  http_server:
    address: ""
    path: /events
    allowed_verbs:
      - POST
output:
  http_client: 
    url : <endpoint> (configured to give 200 for now)
    verb : POST
    propagate_response : true
    extract_headers : 
      include_prefixes: [ "http_status_code" ]
  processors :
    - log:
        fields_mapping: |
          root.event_type = this.type
          root.event_id = this.id
          root.status_code = meta("http_status_code")
```

the output log i'm recieving is : 
```
 path=root.output.processors.0 status_code="<nil>"
```

can anyone please guide me here ?
