### ISSUE TITLE
lint command ignores environment variables

### ISSUE THREAD

**Issue by artemklevtsov** [redpanda-data/benthos#223]
Hi,

Seems lint not react for the environment variables.

Config example:

```yaml
http:
  enabled: false

logger:
  level: debug
  format: json

input:
  kafka_franz:
    seed_brokers:
      - ${KAFKA_BROKERS:localhost:9092}
    topics:
      - srv.errors
    consumer_group: ${KAFKA_CONSUMER_GROUP:""}
    # start_offset: earliest
    sasl:
      - mechanism: ${KAFKA_SASL_MECHANISM:"none"}
        username: ${KAFKA_SASL_USER:""}
        password: ${KAFKA_SASL_PASSWORD:""}
    batching:
      count: 50
      period: 1s

pipeline:
  processors:
    - mapping: |
        #!blobl

        root = this.payload
    - log:
        message: processed
        fields_mapping: |
          #!blobl

          root.count = counter()

output:
  # stdout: {}
  kafka_franz:
    seed_brokers:
      - ${KAFKA_BROKERS:localhost:9092}
    topic: srv
    timestamp_ms: ${! metadata("kafka_timestamp_ms") }
    sasl:
      - mechanism: ${KAFKA_SASL_MECHANISM:"none"}
        username: ${KAFKA_SASL_USER:""}
        password: ${KAFKA_SASL_PASSWORD:""}
    batching:
      count: 50
      period: 1s
```

Trying to lint:

```sh
❯ redpanda-connect lint --skip-env-var-check tmp/config.yaml
tmp/config.yaml(10,1) a consumer group is mandatory when not using explicit topic partitions
❯ KAFKA_CONSUMER_GROUP=test  redpanda-connect lint --skip-env-var-check tmp/config.yaml
tmp/config.yaml(10,1) a consumer group is mandatory when not using explicit topic partitions
```
