### ISSUE TITLE
Feature Request: Pipeline-to-Pipeline communication

### ISSUE THREAD

**Issue by danriedl** [redpanda-data/benthos#55]
As a benthos (the core) user i want to be able to have a possibility to stitch together stream configs, so it acts as a pipeline-to-pipeline communication.
This would allow me to:

- break-up the complexity of large pipelines.
- implement various architectural patterns, such as the Distributor pattern, the Output Isolator pattern, the Forked Path pattern, and the Collector pattern.
- have better manageability, because only individual pipelines needed to be changed instead of the big chonker.

**This would be a Mock:**
reader.yaml
```yaml
input:
  generate:
    mapping: "hello"
pipeline:
  processors: []
output:
  pipeline:
    send_to: ["myVirtualAddress"] 
```

writer.yaml
```yaml
input:
  pipeline:
    address: "myVirtualAddress"
pipeline:
  processors: []
output:
  stdout: {}
```
