### ISSUE TITLE
Support waiting on cache entries

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [redpanda-data/benthos#72]
Currently waiting for cache entries is quite a bit of config:

```yaml
- while:
    at_least_once: true
    check: errored()
    processors:
    - cache:
        resource: mem
        operator: get
        key: my_key
```

all this could be replaced by more straight-forward:

```yaml
- cache:
    resource: mem
    operator: wait
    key: my_key
```
